name: FE build action

on: [push]

jobs:
    build:
        name: Build & Release
        if: "!contains(github.event.head_commit.author, 'action@github.com')"
        runs-on: ubuntu-latest
        steps:
            - name: set env
              run: echo BRANCH=$(echo -n "${GITHUB_REF#refs/heads/}") >> $GITHUB_ENV
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: 10
            - run: npm i
            - name: Run linters
              uses: wearerequired/lint-action@v1
              with:
                  github_token: ${{ secrets.github_token }}
                  eslint: true
                  eslint_dir: ./src
                  eslint_extensions: js,ts,tsx
                  prettier: true
            - name: Bump version
              if: startsWith(env.BRANCH,'release') == true
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  npm run release
            - name: Push changes
              if: startsWith(env.BRANCH,'release') == true
              uses: ad-m/github-push-action@master
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  branch: ${{env.BRANCH}}
                  force: true
                  tags: true
            - name: test and build
              run: |
                  echo "127.0.0.1 diakonie.local" | sudo tee -a /etc/hosts
                  npm run test
                  npm run build
